---
title: "S311 Research Project"
author: "Emily Rose Stringer"
output: html_document
---

```{r load-packages, message=FALSE}
#install.packages('tidyverse')
library(tidyverse)
#install.packages('readr')
library(readr)
#install.packages('dplyr')
library(dplyr)
#install.packages('janitor')
library(janitor)
library(sp)
library(leaflet)
library(ggplot2)
```

```{r read-in-datasets, include=FALSE}
S311_measures <- read_csv("~/Documents/repos/S311-plankton-research/data/S311_measures.csv")
measures <- read_csv("~/Documents/repos/S311-plankton-research/data/measures.csv")
S311_data <- read_csv("~/Documents/repos/S311-plankton-research/data/S311_data.csv")
S311_meta <- read_csv("~/Documents/repos/S311-plankton-research/data/S311_meta.csv")
meta_data <- read_csv("~/Documents/repos/S311-plankton-research/data/meta_data.csv")
meta2 <- read_csv("~/Documents/repos/S311-plankton-research/data/meta2.csv")
use_this_meta <- read_csv("~/Documents/repos/S311-plankton-research/data/use_this_meta.csv")
```

```{r leaflet-map}
leaflet(data = S311_data) %>%
  addProviderTiles(providers$OpenTopoMap) %>%
  setView(lng = -176,
          lat = -22,
          zoom = 3.5) %>%
  addCircleMarkers(~long, ~lat, 
                    radius = 6,
                   color = "#ff6633",
                   stroke = FALSE,
                    fillOpacity = 0.75)
```

###Summarizing data

```{r chl-concentration}
S311_data %>%
ggplot(aes(x = station, y = chl_a_concentration)) + 
  geom_line() + 
  geom_point() +
  theme_minimal()
```

```{r cope-biomass}
meta_data %>%
  filter(cope_or_chae == "copepod") %>%
ggplot(aes(x = station, y = biomass)) + 
  geom_line() + 
  geom_point() +
  theme_minimal()
```

```{r chae-biomass}
meta_data %>%
  filter(cope_or_chae == "chaetognath") %>%
ggplot(aes(x = station, y = biomass)) + 
  geom_line() + 
  geom_point() +
  theme_minimal()
```

```{r juvenile-chaetognaths}
measures %>%
  select(cope_or_chae, functional_group) %>%
  filter(functional_group == "chaetognath juvenile") %>%
  count()

# 104 chaetognaths total, 72 adults (69.2%), 32 juveniles(30.7%).

measures %>%
  select(cope_or_chae, functional_group) %>%
  filter(cope_or_chae == "copepod") %>%
  count()

# 106 total copepods, 105 herbivores (99%), 1 carnivore (0.9%)
```


```{r comparison-of-cop-chae}
meta2 <- meta_data %>%
  group_by(station, cope_or_chae) %>%
  mutate(biomass_cop = case_when(
                              cope_or_chae == "copepod" ~ biomass))
write_csv(meta2, file = "~/Documents/repos/S311-plankton-research/meta2.csv")

use_this_meta %>%
  ggplot(aes(x = station, color = c_c)) +
  geom_line(aes(x = station, y = biomass_cop), size = 1) +
  geom_line(aes(x = station, y = num_juv), size = 1) +
  geom_line(aes(x = station, y = num_adult), size = 1) +
 theme_minimal() + 
  theme(plot.caption = element_text(hjust = 0)) +
labs(title = "fig. 2 Chaetognaths and Copepods",
       subtitle = "biomass from hundred counts",
     caption = "Biomass of Copepods and Chaetognaths at each station. 
     The correlation between chaetognaths and copepods indicates that chaetognaths likely impact copepod communities.",
       x = "station", y = "biomass") +
  scale_color_manual(values = c("copepod" = "#238a8d", "adult chaetognath" = "#440154", "juvenile chaetognath" = "#bade28"), name = "")

ggsave("visuals/corrected_fig2.jpg", device = "jpg", dpi = 500)

      
# 104 chaetognaths total, 72 adults (69.2%), 32 juveniles(30.7%).


# since this is biomass (percent of the count) rather than number/100 is it indicative of a relationship or is the relationship still constrained by the fact that this is out of 100
# #/100 would show a false relationship while biomass shows a more realistic relationship of what is in the plankton?
```


```{r copepod-size-distribution}
measures %>%
  mutate(station = factor(station, levels=c("13", "17", "20", "23", "26", "29", "33", "36", "38", "42", "44"))) %>%
  filter(cope_or_chae == "copepod") %>%
  ggplot(aes(x = station, y = corrected_size)) +
  geom_violin() +
  labs(title = "Size Distribution of Copepods", 
       x = "station", y = "copepod length (mm)") + 
  theme_minimal()
```

```{r copepod-stats}
measures %>%
  select(station, corrected_size, cope_or_chae) %>%
  group_by(station) %>%
  filter(cope_or_chae == "copepod") %>%
  summarise(median = median(corrected_size, na.rm = TRUE), 
            max = max(corrected_size, na.rm = TRUE),
            min = min(corrected_size, na.rm = TRUE),
            mean = mean(corrected_size, na.rm = TRUE), 
              sd = sd(corrected_size, na.rm = TRUE), 
               IQR = IQR(corrected_size, na.rm = TRUE))
```


```{r chaetognath-size-distribution}
measures %>%
  mutate(station = factor(station, levels=c("13", "17", "20", "23", "26", "29", "33", "36", "38", "42", "44"))) %>%
  filter(cope_or_chae == "chaetognath") %>%
  ggplot(aes(x = station, y = corrected_size, fill = size_class, color = size_class)) +
  geom_violin() +
  labs(title = "Size Distribution of Copepods", 
       x = "station", y = "chaetognath length (mm)") + 
  theme_minimal() + 
  scale_color_manual(values = c("chaetognath adult" = "#a0da39", "chaetognath juvenile" = "#365c8d"), guide = "none") +
  scale_fill_manual(values = c("chaetognath adult" = "#a0da39", "chaetognath juvenile" = "#365c8d"))
```

```{r copepods-chla}
copColor <- "#238a8d"
chlaColor <- "#bade28"

 # mutate(station = factor(station, levels=c("13", "17", "20", "23", "26", "29", "33", "36", "38", "42", "44"))) %>%
   
ggplot(S311_data, aes(x = station)) +
    geom_line(aes(x = station, y = biomass_copepods), size = 1, color = "#238a8d") +
    geom_area(aes(x = station, y = chl_a_concentration *100), size = 1, color = "#bade28", fill = "#bade28") +
    # geom_line(aes(x = station, y = biomass_chaetognaths), size = 1, color = "#238a8d") +
    scale_y_continuous(name = "copepod biomass", sec.axis = sec_axis( trans=~./100, name="Chl-a concentration")) +
      theme_minimal()+
    theme(axis.title.y = element_text(color = copColor),
          axis.title.y.right = element_text(color = chlaColor), 
          plot.caption = element_text(hjust = 0))+
    labs(title = "fig. 5 Copepods and Chloropyll-a concentration", 
         caption = "Copepod biomass and chlorophyll-a concentration at each station. 
         A decline in chlorophyll-a concentration corresponds to a decline in copepod biomass, but overall there is little correlation.") 

ggsave("visuals/corrected_fig5.jpg", device = "jpg", dpi = 500)
```

```{r}
S311_meta %>%
  mutate(station = factor(station, levels=c("13", "17", "20", "23", "26", "29", "33", "36", "38", "42", "44"))) %>%
  group_by(station) %>%
  ggplot(aes(x = station, y = biomass, fill = cope_or_chae)) +
  geom_col() +
  scale_fill_manual(values = c("copepod" = "#238a8d", "chaetognath" = "#440154"))
```


```{r chl-a-concentration}
meta_data %>%
# filter(cope_or_chae == "chaetognath") %>%
ggplot(aes(x = chl_a_concentration, y = biomass, color = cope_or_chae)) +
geom_jitter()+
geom_smooth(method= lm)+
  theme_minimal()+
  theme(plot.caption = element_text(hjust = 0)) +
labs(title = "fig. 4 Chlorophyll-a concentration and biomass of Chaetognaths and Copepods",
       subtitle = "biomass from hundred counts", 
     caption = "Copepod and chaetognath biomass measured across chlorophyll-a concentration. 
     Copepods and chaetognaths show a slight increase in overall biomass with the increase of chlorophyll-a.",
       x = "chlorophyll-a concentration", y = "biomass") + 
  scale_color_manual(values = c("copepod" = "#238a8d", "chaetognath" = "#440154"), name = "")
   
ggsave("visuals/corrected_fig4.jpg", device = "jpg", dpi = 500) 
```

```{r}
measures %>% 
  select(station, cope_or_chae, functional_group) %>%
   add_column(subsample = "20") %>% # take this and pipe into the next graph
  add_column(count_cc = "1") %>% # group_by station and count cope_or_chae to understand the total in the sample
  group_by(station, cope_or_chae) %>%
  count(count_cc, functional_group) %>% 
  group_by(cope_or_chae) %>%
      ggplot(aes(x = station, y = n, fill = functional_group)) +
      geom_col() +
  theme_minimal() +
  theme(plot.caption = element_text(hjust = 0)) +
      labs(title = "fig. 3 Proportion of Chaetognaths and Copepods",
            subtitle = "measured from subsample", 
           caption = "Proportion of herbivorous/ omnivorous vs carnivorous copepods and adult vs juvenile chaetognaths.
           The vast majority (99%) of copepods are herbivorous/ omnivorous.
           There is a fairly even proportion of juvenile to adult chaetognaths.",
            x = "station", y = "proportion") + 
       # scale_fill_manual(values = c("copepod" = "#238a8d", "chaetognath" = "#440154"), name = "") +
       scale_fill_manual(values = c("copepod (herbivorous/ omnivorous)" = "#29af7f", "copepod (carnivorous)" = "#bade28", "chaetognath adult" = "#440154", "chaetognath juvenile" = "#2d718e"), name = "")
        
  ggsave("visuals/corrected_fig3.jpg", device = "jpg", dpi = 500)
```

```{r}
measures %>%
  mutate(chl_a_concentration = case_when(
    station == "13" ~ "0.1", 
    station == "17" ~ "0.1",
    station == "20" ~ "0.05",
    station == "23" ~ "0.04",
    station == "26" ~ "0.05",
    station == "29" ~ "0.09",
    station == "33" ~ "0.11",
    station == "36" ~ "0.13",
    station == "38" ~ "0.11",
    station == "42" ~ "0.05",
    station == "44" ~ "0.07")) %>%
  mutate(chl_a_concentration = as.numeric(chl_a_concentration)) %>%
  filter(cope_or_chae == "copepod") %>%
  ggplot(aes(x = chl_a_concentration, y = corrected_size)) + 
  geom_jitter(color = "#2d718e") +
  geom_smooth(color = "#2d718e")+
  theme_minimal()+
  theme(plot.caption = element_text(hjust = 0)) +
    labs(title = "fig. 6 Copepod Size and Chloropyll-a concentration",
         caption = "Copepod size paired with chlorophyll-a concentration. 
         There is no notable correlation showing that copepod size scales with chlorophyll-a concentration.",
         x = "chlorophyll-a concentration", 
         y = "copepod size")

ggsave("visuals/correct_fig6.jpg", device = "jpg", dpi = 500)

                              
cops <- measures %>%
  filter(cope_or_chae == "copepod")
cops %>%
  median(corrected_size)

cops %>% 
  summarize(median = median(corrected_size, na.rm = TRUE))
```

